# yazi.toml
[mgr]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"
show_symlink = true

[preview]
wrap = "yes"
image_filter = "nearest"
image_bound = 0
max_width = 10000
max_height = 10000

